# Generated by Django 6.1.1 on 2026-09-13 21:13

import apps.listings.models
import django.core.validators
import django.db.models.manager
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalListing',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('title', models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', verbose_name='Описание')),
                ('city', models.CharField(help_text='City as displayed, e.g. Köln', max_length=100, verbose_name='Город')),
                ('city_normalized', models.CharField(db_index=True, editable=False, help_text='Folded lowercase form used for search: Köln, Koeln and koln all become koeln', max_length=100, verbose_name='Город (поиск)')),
                ('district', models.CharField(blank=True, help_text='District or quarter, optional', max_length=100, verbose_name='Район')),
                ('address', models.CharField(blank=True, help_text='Street and house number, e.g. Hohe Straße 12. Optional', max_length=200, verbose_name='Адрес')),
                ('postal_code', models.CharField(blank=True, help_text='Postal code, e.g. 50667. Optional', max_length=16, verbose_name='Индекс')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night in EUR, e.g. 89.50', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за ночь')),
                ('rooms', models.PositiveSmallIntegerField(help_text='Number of rooms, from 1 to 50', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Комнат')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('studio', 'Студия'), ('room', 'Комната')], help_text='apartment, house, studio or room', max_length=16, verbose_name='Тип жилья')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive listings are hidden from search but keep their bookings', verbose_name='Активно')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Объявление',
                'verbose_name_plural': 'historical Объявления',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('title', models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', verbose_name='Описание')),
                ('city', models.CharField(help_text='City as displayed, e.g. Köln', max_length=100, verbose_name='Город')),
                ('city_normalized', models.CharField(db_index=True, editable=False, help_text='Folded lowercase form used for search: Köln, Koeln and koln all become koeln', max_length=100, verbose_name='Город (поиск)')),
                ('district', models.CharField(blank=True, help_text='District or quarter, optional', max_length=100, verbose_name='Район')),
                ('address', models.CharField(blank=True, help_text='Street and house number, e.g. Hohe Straße 12. Optional', max_length=200, verbose_name='Адрес')),
                ('postal_code', models.CharField(blank=True, help_text='Postal code, e.g. 50667. Optional', max_length=16, verbose_name='Индекс')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night in EUR, e.g. 89.50', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за ночь')),
                ('rooms', models.PositiveSmallIntegerField(help_text='Number of rooms, from 1 to 50', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Комнат')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('studio', 'Студия'), ('room', 'Комната')], help_text='apartment, house, studio or room', max_length=16, verbose_name='Тип жилья')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive listings are hidden from search but keep their bookings', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ('-created_at', '-id'),
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='JPEG or PNG, at least 800x600 px', upload_to=apps.listings.models.listing_photo_path, verbose_name='Фото')),
                ('caption', models.CharField(blank=True, help_text="Optional caption, e.g. 'Living room'", max_length=200, verbose_name='Подпись')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Display order, ascending. The lowest value is the cover photo', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Фото объявления',
                'verbose_name_plural': 'Фото объявлений',
                'ordering': ('position', 'id'),
            },
        ),
    ]
