# Generated by Django 6.1.1 on 2026-09-15 23:08

import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_price_base(apps, schema_editor):
    """
    Backfills price_base for listings that already exist. Without this
    step the old rows would keep the zero from the default and the price
    filter would treat them as free.
    """
    from django.conf import settings
    from djmoney.contrib.exchange.models import convert_money
    from djmoney.money import Money

    Listing = apps.get_model("listings", "Listing")
    for listing in Listing.objects.all().iterator():
        currency = listing.price_per_night_currency
        amount = listing.price_per_night
        if currency == settings.BASE_CURRENCY:
            listing.price_base = amount
        else:
            # the rates may not be loaded by update_rates yet — then fall
            # back to the raw value, exactly as Listing.save() does.
            try:
                listing.price_base = convert_money(
                    Money(amount, currency), settings.BASE_CURRENCY
                ).amount
            except Exception:
                listing.price_base = amount
        listing.save(update_fields=["price_base"])


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_fulltext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_city_rooms_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_city_type_price_idx',
        ),
        migrations.AddField(
            model_name='historicallisting',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Computed automatically, used for filtering and sorting', max_digits=12, verbose_name='Price in base currency'),
        ),
        migrations.AddField(
            model_name='historicallisting',
            name='price_per_night_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'CZK Kč'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Computed automatically, used for filtering and sorting', max_digits=12, verbose_name='Price in base currency'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_night_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'CZK Kč'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='price_per_night',
            field=djmoney.models.fields.MoneyField(decimal_places=2, help_text='Price per one night in the chosen currency, e.g. 89.50', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per night'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room')], help_text='apartment, house, studio or room', max_length=16, verbose_name='Тип жилья'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=djmoney.models.fields.MoneyField(decimal_places=2, help_text='Price per one night in the chosen currency, e.g. 89.50', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per night'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room')], help_text='apartment, house, studio or room', max_length=16, verbose_name='Тип жилья'),
        ),
        # before the price_base indexes are built — the values must be
        # real by the time the index is created.
        migrations.RunPython(backfill_price_base, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city_normalized', 'rooms', 'price_base'], name='listing_city_rooms_price_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city_normalized', 'property_type', 'price_base'], name='listing_city_type_price_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_night_currency__in', ('EUR', 'USD', 'GBP', 'PLN', 'CZK'))), name='listing_currency_valid', violation_error_message='Unsupported currency.'),
        ),
        migrations.AlterConstraint(
            model_name='listing',
            name='listing_price_gt_zero',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_night__gt', 0)), name='listing_price_gt_zero', violation_error_message='Price must be greater than zero.'),
        ),
        migrations.AlterConstraint(
            model_name='listing',
            name='listing_rooms_gte_one',
            constraint=models.CheckConstraint(condition=models.Q(('rooms__gte', 1)), name='listing_rooms_gte_one', violation_error_message='A listing must have at least one room.'),
        ),
        migrations.AlterConstraint(
            model_name='listing',
            name='listing_property_type_valid',
            constraint=models.CheckConstraint(condition=models.Q(('property_type__in', ['apartment', 'house', 'studio', 'room'])), name='listing_property_type_valid', violation_error_message='Unknown property type.'),
        ),
    ]
