# Generated by Django 6.1.1 on 2026-09-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_listing_city_rooms_price_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description_de',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_en',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_ru',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_de',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_en',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_ru',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='caption_de',
            field=models.CharField(blank=True, help_text="Optional caption, e.g. 'Living room'", max_length=200, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='caption_en',
            field=models.CharField(blank=True, help_text="Optional caption, e.g. 'Living room'", max_length=200, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='caption_ru',
            field=models.CharField(blank=True, help_text="Optional caption, e.g. 'Living room'", max_length=200, null=True, verbose_name='Подпись'),
        ),
    ]
