# Generated by Django 6.1.1 on 2026-09-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_description_de_listing_description_en_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX listing_search_ft ON listings_listing;",
            reverse_sql="CREATE FULLTEXT INDEX listing_search_ft "
                        "ON listings_listing (title, description);",
        ),
        migrations.RunSQL(
            sql="CREATE FULLTEXT INDEX listing_ft_en "
                "ON listings_listing (title_en, description_en);",
            reverse_sql="DROP INDEX listing_ft_en ON listings_listing;",
        ),
        migrations.RunSQL(
            sql="CREATE FULLTEXT INDEX listing_ft_de "
                "ON listings_listing (title_de, description_de);",
            reverse_sql="DROP INDEX listing_ft_de ON listings_listing;",
        ),
        migrations.RunSQL(
            sql="CREATE FULLTEXT INDEX listing_ft_ru "
                "ON listings_listing (title_ru, description_ru);",
            reverse_sql="DROP INDEX listing_ft_ru ON listings_listing;",
        ),
    ]
