# Generated by Django 6.1.1 on 2026-09-16 00:09

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_fulltext_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='price_per_night',
            field=djmoney.models.fields.MoneyField(decimal_places=2, help_text='Price per one night in the chosen currency, e.g. 89.50', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))], verbose_name='Price per night'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=djmoney.models.fields.MoneyField(decimal_places=2, help_text='Price per one night in the chosen currency, e.g. 89.50', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))], verbose_name='Price per night'),
        ),
    ]
