# Generated by Django 6.1.1 on 2026-09-18 00:53

import apps.listings.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_historicallisting_description_de_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallisting',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Listing', 'verbose_name_plural': 'historical Listings'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'base_manager_name': 'all_objects', 'ordering': ('-created_at', '-id'), 'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AlterModelOptions(
            name='listingphoto',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Listing photo', 'verbose_name_plural': 'Listing photos'},
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='address',
            field=models.CharField(blank=True, help_text='Street and house number, e.g. Hohe Straße 12. Optional', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='city',
            field=models.CharField(help_text='City as displayed, e.g. Köln', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='city_normalized',
            field=models.CharField(db_index=True, editable=False, help_text='Folded lowercase form used for search: Köln, Koeln and koln all become koeln', max_length=100, verbose_name='City (search)'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='description',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='description_de',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='description_en',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='description_ru',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='district',
            field=models.CharField(blank=True, help_text='District or quarter, optional', max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive listings are hidden from search but keep their bookings', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code, e.g. 50667. Optional', max_length=16, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room')], help_text='apartment, house, studio or room', max_length=16, verbose_name='Property type'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='rooms',
            field=models.PositiveSmallIntegerField(help_text='Number of rooms, from 1 to 50', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='title',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='title_de',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='title_en',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='title_ru',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, help_text='Street and house number, e.g. Hohe Straße 12. Optional', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(help_text='City as displayed, e.g. Köln', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city_normalized',
            field=models.CharField(db_index=True, editable=False, help_text='Folded lowercase form used for search: Köln, Koeln and koln all become koeln', max_length=100, verbose_name='City (search)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description_de',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description_en',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description_ru',
            field=models.TextField(help_text='Full description: layout, furniture, neighbourhood, house rules', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, help_text='District or quarter, optional', max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive listings are hidden from search but keep their bookings', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code, e.g. 50667. Optional', max_length=16, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room')], help_text='apartment, house, studio or room', max_length=16, verbose_name='Property type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveSmallIntegerField(help_text='Number of rooms, from 1 to 50', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title_de',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title_en',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title_ru',
            field=models.CharField(help_text="Short headline shown in search results, e.g. 'Bright 2-room flat near Rhine'", max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='caption',
            field=models.CharField(blank=True, help_text="Optional caption, e.g. 'Living room'", max_length=200, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='caption_de',
            field=models.CharField(blank=True, help_text="Optional caption, e.g. 'Living room'", max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='caption_en',
            field=models.CharField(blank=True, help_text="Optional caption, e.g. 'Living room'", max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='caption_ru',
            field=models.CharField(blank=True, help_text="Optional caption, e.g. 'Living room'", max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(help_text='JPEG or PNG, at least 800x600 px', upload_to=apps.listings.models.listing_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order, ascending. The lowest value is the cover photo', verbose_name='Position'),
        ),
    ]
