"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
import logging.config

BASE_DIR = Path(__file__).resolve().parent.parent

# load .env from the project root before any variable is accessed
load_dotenv(BASE_DIR / ".env")


def env_bool(key: str, default: bool = False) -> bool:
    """
    Casts an environment string to bool. A bare bool("False") evaluates to True.
    """
    return os.getenv(key, str(default)).strip().lower() in ("1", "true", "yes", "on")


def env_list(key: str, default: str = "") -> list[str]:
    """
    Parses a comma-separated list of values.
    """
    return [item.strip() for item in os.getenv(key, default).split(",") if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# no default — the app must not start without a key
SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = env_bool("DEBUG", False)

# behind nginx Django sees only its connection. Without trusting the
# X-Forwarded-Proto header it builds http:// links under HTTPS, and the
# CSRF check starts rejecting POST forms from the admin.
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", "http://localhost")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "djmoney",
    # contrib.exchange stores the rates and provides convert_money()
    "djmoney.contrib.exchange",

# third-party
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",

    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    "drf_spectacular",
    "drf_standardized_errors",
    "simple_history",
# local
    "apps.users",
    "apps.listings",
    "apps.bookings",
    "apps.reviews",
    "apps.analytics",
    "core",
]

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"
MODELTRANSLATION_LANGUAGES = ("en", "de", "ru")
# when a translation is missing, fall back to the default language
MODELTRANSLATION_FALLBACK_LANGUAGES = ("en",)

# the project's base currency. Anything that must be compared or sorted
# is converted into it in a denormalised column.
BASE_CURRENCY = "EUR"
DEFAULT_CURRENCY = "EUR"

# limits the dropdown and the values of the *_currency column
CURRENCIES = ("EUR", "USD", "GBP", "PLN", "CZK")
CURRENCY_CHOICES = [
    ("EUR", "EUR €"), ("USD", "USD $"), ("GBP", "GBP £"),
    ("PLN", "PLN zł"), ("CZK", "CZK Kč"),
]

# a local fixed-rate backend: deterministic and needs neither network access
# nor an API key. To use live rates, point this at another djmoney backend
# (e.g. OpenExchangeRatesBackend); no other code changes are needed.
EXCHANGE_BACKEND = "apps.listings.exchange.StaticExchangeBackend"

# must be set before the first migration and never changed afterwards
AUTH_USER_MODEL = "users.User"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.RequestLogMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.QueryCountMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
#------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    # our handler rather than the library one — see core/exceptions.py
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "core.pagination.DefaultPagination",
    "PAGE_SIZE": 20,
}

DRF_STANDARDIZED_ERRORS = {
    # in development unhandled exceptions use the same format too —
    # otherwise a 500 arrives as raw HTML and is awkward to read.
    "ENABLE_IN_DEBUG_FOR_UNHANDLED_EXCEPTIONS": DEBUG,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Booking API",
    "DESCRIPTION": "Housing rental booking service",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # the postprocessing hook writes error schemas into the OpenAPI
    # document — without it Swagger shows successful responses only.
    "POSTPROCESSING_HOOKS": [
        "drf_standardized_errors.openapi_hooks.postprocess_schema_enums"
    ],
    # without the overrides spectacular warns about enum name collisions:
    # the same sets of codes appear in the schema many times.
    "ENUM_NAME_OVERRIDES": {
        "ValidationErrorEnum": "drf_standardized_errors.openapi_serializers.ValidationErrorEnum.choices",
        "ClientErrorEnum": "drf_standardized_errors.openapi_serializers.ClientErrorEnum.choices",
        "ServerErrorEnum": "drf_standardized_errors.openapi_serializers.ServerErrorEnum.choices",
        "ErrorCode401Enum": "drf_standardized_errors.openapi_serializers.ErrorCode401Enum.choices",
        "ErrorCode403Enum": "drf_standardized_errors.openapi_serializers.ErrorCode403Enum.choices",
        "ErrorCode404Enum": "drf_standardized_errors.openapi_serializers.ErrorCode404Enum.choices",
        "ErrorCode405Enum": "drf_standardized_errors.openapi_serializers.ErrorCode405Enum.choices",
        "ErrorCode406Enum": "drf_standardized_errors.openapi_serializers.ErrorCode406Enum.choices",
        "ErrorCode415Enum": "drf_standardized_errors.openapi_serializers.ErrorCode415Enum.choices",
        "ErrorCode429Enum": "drf_standardized_errors.openapi_serializers.ErrorCode429Enum.choices",
        "ErrorCode500Enum": "drf_standardized_errors.openapi_serializers.ErrorCode500Enum.choices",
    },
}

   #----------------------------------------------------
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# MySQL is the production database. DB_ENGINE=sqlite switches to a local
# SQLite file, e.g. to run the test suite without a MySQL server; FULLTEXT
# search then falls back to icontains.
if os.getenv("DB_ENGINE", "mysql").lower() == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USER"],
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {
                # strict mode — MySQL raises an error instead of silently truncating data
                "sql_mode": "STRICT_TRANS_TABLES",
                "charset": "utf8mb4",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", _("English")),
    ("de", _("German")),
    ("ru", _("Russian")),
]
LOCALE_PATHS = [BASE_DIR / "locale"]
USE_I18N = True
USE_TZ = True
TIME_ZONE = "Europe/Berlin"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
# collectstatic target, served by nginx in Docker
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# how many days before check-in a booking may still be cancelled —
# read by Booking.is_cancellable() so the rule is not hard-coded.
BOOKING_CANCELLATION_DAYS = int(os.getenv("BOOKING_CANCELLATION_DAYS", "1"))

# how many days after posting the author may still edit a review —
# read by Review.is_editable() so the rule is not hard-coded.
REVIEW_EDIT_WINDOW_DAYS = int(os.getenv("REVIEW_EDIT_WINDOW_DAYS", "14"))

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# EMAIL_BACKEND is a dotted path string, not a dict like DATABASES.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@booking.local")
SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000")

TESTING = "test" in sys.argv

if TESTING:
    # emails go into mail.outbox instead of being printed
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
    # a fast hasher: the default PBKDF2 makes every created user cost ~0.5s
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]

LOG_DIR = BASE_DIR / "logs"
# test runs stay quiet unless LOG_LEVEL is set explicitly
LOG_LEVEL = os.getenv("LOG_LEVEL", "WARNING" if TESTING else "INFO").upper()
# inside a container log to stdout only: files vanish with the container,
# and log collection is the platform's job (Docker, CloudWatch).
LOG_TO_FILE = env_bool("LOG_TO_FILE", not env_bool("IN_CONTAINER", False))
# SQL is emitted only with DEBUG=True — Django wraps the cursor into the
# debug one in that mode alone.
LOG_SQL = env_bool("LOG_SQL", False)
QUERY_COUNT_WARNING = int(os.getenv("QUERY_COUNT_WARNING", "20"))

if LOG_TO_FILE:
    LOG_DIR.mkdir(parents=True, exist_ok=True)

_handlers = ["console"] + (["file"] if LOG_TO_FILE else [])

LOGGING = {
    "version": 1,
    # True would disable Django's own loggers and those of third-party
    # packages — runserver messages and tracebacks would disappear.
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {"()": "core.logging_context.RequestIdFilter"},
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname:<7} [{request_id}] {name}: {message}",
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            # the filter sits on the handler, not the logger — see RequestIdFilter
            "filters": ["request_id"],
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "app.log"),
            # rotation is mandatory, otherwise the file eventually fills the disk
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "verbose",
            "filters": ["request_id"],
        },
    },
    "root": {"handlers": _handlers, "level": "WARNING"},
    "loggers": {
        "django": {
            "handlers": _handlers,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.server": {
            "handlers": _handlers,
            "level": "WARNING",
            "propagate": False,
        },
        # 4xx and 5xx with tracebacks
        "django.request": {
            "handlers": _handlers,
            "level": "WARNING",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if (DEBUG and LOG_SQL) else "WARNING",
            "propagate": False,
        },
        # our own applications: apps.* and core.*
        "apps": {"handlers": _handlers, "level": LOG_LEVEL, "propagate": False},
        "core": {"handlers": _handlers, "level": LOG_LEVEL, "propagate": False},
    },
}