"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# RU: читаем .env из корня проекта до обращения к переменным
# EN: load .env from the project root before any variable is accessed
load_dotenv(BASE_DIR / ".env")


def env_bool(key: str, default: bool = False) -> bool:
    """
    RU: Приводит строку из окружения к bool. Голый bool("False") — это True.
    EN: Casts an environment string to bool. A bare bool("False") evaluates to True.
    """
    return os.getenv(key, str(default)).strip().lower() in ("1", "true", "yes", "on")


def env_list(key: str, default: str = "") -> list[str]:
    """
    RU: Разбирает список значений, разделённых запятыми.
    EN: Parses a comma-separated list of values.
    """
    return [item.strip() for item in os.getenv(key, default).split(",") if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# RU: без значения по умолчанию — приложение не стартует без ключа
# EN: no default — the app must not start without a key
SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = env_bool("DEBUG", False)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "djmoney",
    # RU: contrib.exchange хранит курсы и даёт convert_money()
    # EN: contrib.exchange stores the rates and provides convert_money()
    "djmoney.contrib.exchange",

# third-party
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",

    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    "drf_spectacular",
    "drf_standardized_errors",
    "simple_history",
# local
    "apps.users",
    "apps.listings",
    "apps.bookings",
    "apps.reviews",
    "apps.analytics",
]

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"
MODELTRANSLATION_LANGUAGES = ("en", "de", "ru")
# RU: если перевода нет — показываем язык по умолчанию, а не пустоту
# EN: when a translation is missing, fall back to the default language
MODELTRANSLATION_FALLBACK_LANGUAGES = ("en",)

# RU: базовая валюта проекта. Всё, что нужно сравнивать и сортировать,
#     приводится к ней в денормализованной колонке.
# EN: the project's base currency. Anything that must be compared or sorted
#     is converted into it in a denormalised column.
BASE_CURRENCY = "EUR"
DEFAULT_CURRENCY = "EUR"

# RU: ограничивает выпадающий список и значения колонки *_currency
# EN: limits the dropdown and the values of the *_currency column
CURRENCIES = ("EUR", "USD", "GBP", "PLN", "CZK")
CURRENCY_CHOICES = [
    ("EUR", "EUR €"), ("USD", "USD $"), ("GBP", "GBP £"),
    ("PLN", "PLN zł"), ("CZK", "CZK Kč"),
]

# RU: свой бэкенд с фиксированными курсами — внешний API требует ключа,
#     а на защите может не быть интернета. Замена на боевой бэкенд —
#     одна строка, это Open/Closed на практике.
# EN: a local fixed-rate backend — an external API needs a key and there may
#     be no internet during the defence. Swapping in a production backend is
#     a one-line change: Open/Closed in practice.
EXCHANGE_BACKEND = "apps.listings.exchange.StaticExchangeBackend"

AUTH_USER_MODEL = "users.User"      # до первой миграции!


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
#------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # RU: наш обработчик, а не библиотечный напрямую — см. core/exceptions.py
    # EN: our handler rather than the library one — see core/exceptions.py

    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "core.pagination.DefaultPagination",
    "PAGE_SIZE": 20,
}

DRF_STANDARDIZED_ERRORS = {
    # RU: в разработке показываем и необработанные исключения в том же
    #     формате — иначе 500 приходит голым HTML и его неудобно читать.
    # EN: in development unhandled exceptions use the same format too —
    #     otherwise a 500 arrives as raw HTML and is awkward to read.
    "ENABLE_IN_DEBUG_FOR_UNHANDLED_EXCEPTIONS": DEBUG,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Booking API",
    "DESCRIPTION": "Housing rental booking service",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # RU: постпроцессор вписывает схемы ошибок в OpenAPI — без него Swagger
    #     показывает только успешные ответы.
    # EN: the postprocessing hook writes error schemas into the OpenAPI
    #     document — without it Swagger shows successful responses only.
    "POSTPROCESSING_HOOKS": [
        "drf_standardized_errors.openapi_hooks.postprocess_schema_enums"
    ],
    # RU: без переопределений spectacular ругается на коллизии имён enum:
    #     одинаковые наборы кодов встречаются в схеме много раз.
    # EN: without the overrides spectacular warns about enum name collisions:
    #     the same sets of codes appear in the schema many times.
    "ENUM_NAME_OVERRIDES": {
        "ValidationErrorEnum": "drf_standardized_errors.openapi_serializers.ValidationErrorEnum.choices",
        "ClientErrorEnum": "drf_standardized_errors.openapi_serializers.ClientErrorEnum.choices",
        "ServerErrorEnum": "drf_standardized_errors.openapi_serializers.ServerErrorEnum.choices",
        "ErrorCode401Enum": "drf_standardized_errors.openapi_serializers.ErrorCode401Enum.choices",
        "ErrorCode403Enum": "drf_standardized_errors.openapi_serializers.ErrorCode403Enum.choices",
        "ErrorCode404Enum": "drf_standardized_errors.openapi_serializers.ErrorCode404Enum.choices",
        "ErrorCode405Enum": "drf_standardized_errors.openapi_serializers.ErrorCode405Enum.choices",
        "ErrorCode406Enum": "drf_standardized_errors.openapi_serializers.ErrorCode406Enum.choices",
        "ErrorCode415Enum": "drf_standardized_errors.openapi_serializers.ErrorCode415Enum.choices",
        "ErrorCode429Enum": "drf_standardized_errors.openapi_serializers.ErrorCode429Enum.choices",
        "ErrorCode500Enum": "drf_standardized_errors.openapi_serializers.ErrorCode500Enum.choices",
    },
}

   #----------------------------------------------------
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ["DB_NAME"],
        "USER": os.environ["DB_USER"],
        "PASSWORD": os.environ["DB_PASSWORD"],
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            # RU: строгий режим — MySQL вернёт ошибку вместо тихого обрезания данных
            # EN: strict mode — MySQL raises an error instead of silently truncating data
            "sql_mode": "STRICT_TRANS_TABLES",
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", _("English")),
    ("de", _("German")),
    ("ru", _("Russian")),
]
LOCALE_PATHS = [BASE_DIR / "locale"]
USE_I18N = True
USE_TZ = True
TIME_ZONE = "Europe/Berlin"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"   # сюда соберёт collectstatic в Docker

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# RU: за сколько дней до заезда ещё можно отменить бронь — читает
#     Booking.is_cancellable(), чтобы правило не было зашито в код.
# EN: how many days before check-in a booking may still be cancelled —
#     read by Booking.is_cancellable() so the rule is not hard-coded.
BOOKING_CANCELLATION_DAYS = int(os.getenv("BOOKING_CANCELLATION_DAYS", "1"))

# RU: сколько дней после публикации автор ещё может править отзыв —
#     читает Review.is_editable(), правило не зашито в код.
# EN: how many days after posting the author may still edit a review —
#     read by Review.is_editable() so the rule is not hard-coded.
REVIEW_EDIT_WINDOW_DAYS = int(os.getenv("REVIEW_EDIT_WINDOW_DAYS", "14"))

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# RU: EMAIL_BACKEND — строка с путём к классу, а не словарь, как DATABASES.
# EN: EMAIL_BACKEND is a dotted path string, not a dict like DATABASES.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
