# Generated by Django 6.1.1 on 2026-09-13 21:13

import django.core.validators
import django.utils.timezone
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField(help_text='Check-in date, inclusive. Format YYYY-MM-DD', verbose_name='Заезд')),
                ('end_date', models.DateField(help_text='Check-out date, exclusive: this night is not charged', verbose_name='Выезд')),
                ('guests', models.PositiveSmallIntegerField(default=1, error_messages={'invalid': 'Количество гостей должно быть больше нуля.', 'null': 'Укажите количество гостей.'}, help_text='Number of guests, from 1 to 20', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Гостей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', help_text='Lifecycle status. Changed only through the booking actions', max_length=16, verbose_name='Статус')),
                ('price_per_night_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Discount applied at booking time, 0 to 100 percent', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, help_text='Agreed contract amount. Frozen at booking time, never recomputed later', max_digits=12, verbose_name='Итого')),
                ('listing_title_snapshot', models.CharField(max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ('-created_at', '-id'),
                'permissions': [('confirm_booking', 'Can confirm booking'), ('reject_booking', 'Can reject booking'), ('cancel_booking', 'Can cancel booking')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('start_date', models.DateField(help_text='Check-in date, inclusive. Format YYYY-MM-DD', verbose_name='Заезд')),
                ('end_date', models.DateField(help_text='Check-out date, exclusive: this night is not charged', verbose_name='Выезд')),
                ('guests', models.PositiveSmallIntegerField(default=1, error_messages={'invalid': 'Количество гостей должно быть больше нуля.', 'null': 'Укажите количество гостей.'}, help_text='Number of guests, from 1 to 20', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Гостей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', help_text='Lifecycle status. Changed only through the booking actions', max_length=16, verbose_name='Статус')),
                ('price_per_night_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Discount applied at booking time, 0 to 100 percent', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, help_text='Agreed contract amount. Frozen at booking time, never recomputed later', max_digits=12, verbose_name='Итого')),
                ('listing_title_snapshot', models.CharField(max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Бронирование',
                'verbose_name_plural': 'historical Бронирования',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
