# Generated by Django 6.1.1 on 2026-09-13 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='listing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'start_date', 'end_date'], name='booking_listing_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='booking_end_after_start', violation_error_message='Дата выезда должна быть позже даты заезда.'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('guests__gte', 1)), name='booking_guests_gte_one', violation_error_message='Количество гостей должно быть не меньше одного.'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='booking_total_price_gte_zero', violation_error_message='Итоговая сумма не может быть отрицательной.'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_night_snapshot__gt', 0)), name='booking_snapshot_price_positive', violation_error_message='Цена за ночь должна быть положительной.'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'rejected', 'cancelled', 'completed'])), name='booking_status_valid', violation_error_message='Недопустимый статус бронирования.'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__lte', 100)), name='booking_discount_max_100', violation_error_message='Скидка не может превышать 100 процентов.'),
        ),
    ]
