# Generated by Django 6.1.1 on 2026-09-15 23:08

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), editable=False, max_digits=18, verbose_name='Exchange rate at booking time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_night_snapshot_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'CZK Kč'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Total in base currency'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'CZK Kč'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), editable=False, max_digits=18, verbose_name='Exchange rate at booking time'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='price_per_night_snapshot_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'CZK Kč'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='total_price_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Total in base currency'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='total_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'CZK Kč'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_night_snapshot',
            field=djmoney.models.fields.MoneyField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, editable=False, help_text='Agreed contract amount, frozen at booking time', max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='price_per_night_snapshot',
            field=djmoney.models.fields.MoneyField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='total_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, editable=False, help_text='Agreed contract amount, frozen at booking time', max_digits=12, verbose_name='Total'),
        ),
    ]
