# Generated by Django 6.1.1 on 2026-09-18 00:53

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_exchange_rate_and_more'),
        ('listings', '0009_alter_historicallisting_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-created_at', '-id'), 'permissions': [('confirm_booking', 'Can confirm booking'), ('reject_booking', 'Can reject booking'), ('cancel_booking', 'Can cancel booking')], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='historicalbooking',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Booking', 'verbose_name_plural': 'historical Bookings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount applied at booking time, 0 to 100 percent', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount, %'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(help_text='Check-out date, exclusive: this night is not charged', verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1, error_messages={'invalid': 'The number of guests must be a whole number.', 'null': 'Please specify the number of guests.'}, help_text='Number of guests, from 1 to 20', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Guests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(help_text='Check-in date, inclusive. Format YYYY-MM-DD', verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Lifecycle status. Changed only through the booking actions', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount applied at booking time, 0 to 100 percent', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount, %'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='end_date',
            field=models.DateField(help_text='Check-out date, exclusive: this night is not charged', verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1, error_messages={'invalid': 'The number of guests must be a whole number.', 'null': 'Please specify the number of guests.'}, help_text='Number of guests, from 1 to 20', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Guests'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='start_date',
            field=models.DateField(help_text='Check-in date, inclusive. Format YYYY-MM-DD', verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Lifecycle status. Changed only through the booking actions', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterConstraint(
            model_name='booking',
            name='booking_end_after_start',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='booking_end_after_start', violation_error_message='The check-out date must be later than the check-in date.'),
        ),
        migrations.AlterConstraint(
            model_name='booking',
            name='booking_guests_gte_one',
            constraint=models.CheckConstraint(condition=models.Q(('guests__gte', 1)), name='booking_guests_gte_one', violation_error_message='There must be at least one guest.'),
        ),
        migrations.AlterConstraint(
            model_name='booking',
            name='booking_total_price_gte_zero',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='booking_total_price_gte_zero', violation_error_message='The total amount cannot be negative.'),
        ),
        migrations.AlterConstraint(
            model_name='booking',
            name='booking_snapshot_price_positive',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_night_snapshot__gt', 0)), name='booking_snapshot_price_positive', violation_error_message='The price per night must be positive.'),
        ),
        migrations.AlterConstraint(
            model_name='booking',
            name='booking_status_valid',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'rejected', 'cancelled', 'completed'])), name='booking_status_valid', violation_error_message='Invalid booking status.'),
        ),
        migrations.AlterConstraint(
            model_name='booking',
            name='booking_discount_max_100',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__lte', 100)), name='booking_discount_max_100', violation_error_message='The discount cannot exceed 100 percent.'),
        ),
    ]
