# Generated by Django 6.1.1 on 2026-09-13 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(db_index=True, max_length=200)),
                ('results_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'История поиска',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingStats',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='stats', serialize=False, to='listings.listing')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='De-duplicated views, one per user per day', verbose_name='Просмотров')),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Статистика объявления',
                'verbose_name_plural': 'Статистика объявлений',
                'indexes': [models.Index(fields=['-views_count'], name='stats_views_desc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('viewed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='view_records', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Просмотр объявления',
                'verbose_name_plural': 'История просмотров',
                'ordering': ('-created_at',),
            },
        ),
    ]
