# Generated by Django 6.1.1 on 2026-09-13 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='listingview',
            constraint=models.UniqueConstraint(fields=('listing', 'user', 'session_key', 'viewed_on'), name='uniq_listing_view_per_day'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['keyword', '-created_at'], name='search_keyword_created_idx'),
        ),
    ]
