# Generated by Django 6.1.1 on 2026-09-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingstats',
            options={'verbose_name': 'Listing statistics', 'verbose_name_plural': 'Listing statistics'},
        ),
        migrations.AlterModelOptions(
            name='listingview',
            options={'ordering': ('-created_at',), 'verbose_name': 'Listing view', 'verbose_name_plural': 'View history'},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ('-created_at',), 'verbose_name': 'Search query', 'verbose_name_plural': 'Search history'},
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='De-duplicated views, one per user per day', verbose_name='Views'),
        ),
    ]
