# Generated by Django 6.1.1 on 2026-09-18 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreview',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Review', 'verbose_name_plural': 'historical Reviews'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'base_manager_name': 'all_objects', 'ordering': ('-created_at', '-id'), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='text',
            field=models.TextField(blank=True, help_text='Free-form review, up to 2000 characters', max_length=2000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, help_text='Free-form review, up to 2000 characters', max_length=2000, verbose_name='Text'),
        ),
    ]
